### ISSUE TITLE
Error when clikcing the green treasure

### ISSUE THREAD

**Issue by dacja** [Skrelpoid/BetterRewardsMod#17]
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.dungeons.AbstractDungeon.returnTrulyRandomColorlessCard()Lcom/megacrit/cardcrawl/cards/AbstractCard;
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:133)
Caused by: java.lang.NoSuchMethodError: com.megacrit.cardcrawl.dungeons.AbstractDungeon.returnTrulyRandomColorlessCard()Lcom/megacrit/cardcrawl/cards/AbstractCard;
	at skrelpoid.betterrewards.shop.LootboxShopItem.getForRoll(LootboxShopItem.java:164)
	at skrelpoid.betterrewards.shop.LootboxShopItem.onPurchase(LootboxShopItem.java:83)
	at skrelpoid.betterrewards.shop.AbstractShopItem.tryPurchase(AbstractShopItem.java:127)
	at skrelpoid.betterrewards.shop.AbstractShopItem.update(AbstractShopItem.java:113)
	at skrelpoid.betterrewards.BetterRewardsMod.updateShopItems(BetterRewardsMod.java:149)
	at skrelpoid.betterrewards.patches.ShopScreenPatches$UpdateShopItems.Insert(ShopScreenPatches.java:26)
	at com.megacrit.cardcrawl.shop.ShopScreen.update(ShopScreen.java:561)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2673)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:892)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:465)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by Skrelpoid** [comment]
This will be fixed with the new Update
